# Default values for speedle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pms: r.authz.fun/speedle-pms:v0.1
  ads: r.authz.fun/speedle-ads:v0.1
  pullPolicy: Always
  pullSecret: "reg-speedle"

service:
  type: ClusterIP
  pmsPort: 6733
  adsPort: 6734

tls:
  certSecret: speedle-server-tls
  certFile: server.crt
  keyFile: server.key
  trustedCAFile: server-ca.crt
  forceClientCert: true

store:
  type: etcd
  etcd:
    endpoint: http://localhost:2379
    # TLS enabled
    # endpoint: https://example-client.default.svc:2379
    # etcdClientCertSecret: etcd-client-tls
    # certFile: etcd-client.crt
    # keyFile: etcd-client.key
    # trustedCAFile: etcd-client-ca.crt
