# this config is created through command
# mixgen adapter -c $GOPATH/src/istio.io/istio/mixer/adapter/speedle/config/config.proto_descriptor -o $GOPATH/src/istio.io/istio/mixer/adapter/speedle/config -s=false -n speedlegrpcadapter -t authorization -o speedlegrpcadapter.yaml
apiVersion: "config.istio.io/v1alpha2"
kind: adapter
metadata:
  name: speedlegrpcadapter
  namespace: istio-system
spec:
  description: 
  session_based: false
  templates:
  - authorization
---
