# Default values for speedle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pms: r.authz.fun/speedle-pms:v0.1
  ads: r.authz.fun/speedle-ads:v0.1
  pullPolicy: Always
  pullSecret: "reg-speedle"

service:
  type: ClusterIP
  pmsPort: 6733
  adsPort: 6734
