apiVersion: v1
kind: Service
metadata:
  name: {{ template "speedle.fullname" . }}
  labels:
    app: speedle
    chart: {{ template "speedle.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pmsPort }}
      targetPort: pms
      protocol: TCP
      name: pms
    - port: {{ .Values.service.adsPort }}
      targetPort: ads
      protocol: TCP
      name: ads
  selector:
    app: speedle
    release: {{ .Release.Name }}
